((nil .
      ((eval . (setq custom-application-directory "~/Projects/OpenGL-app/build/emacs"))
       (eval . (setq custom-application-runnable "./OpenGL-app"))
       (eval . (setq custom-application-test-directory "~/Projects/OpenGL-app/build/emacs/tests"))
       (eval . (setq custom-application-test-runnable "./RunTests"))
       (cmake-ide-project-dir . "~/Projects/OpenGL-app")
       (cmake-ide-build-dir . "~/Projects/OpenGL-app/build/emacs")
       (cmake-ide-cmake-opts . "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++")
       (helm-make-build-dir . "~/Projects/OpenGL-app/build/emacs")
       (helm-make-arguments . "-j7")
       (helm-ctest-dir . "~/Projects/OpenGL-app/build/emacs"))))
